---
- name: Provision instance in AWS
  hosts: localhost
  vars_files:
    - group_vars/all/vars.yaml
  tasks:
    - name: create security group for jitsi-meet
      ec2_group:
        name: jitsi-videobridge
        description: security group jitsi-meet
        vpc_id: "{{ ec2_vpcid }}"
        region: "{{ ec2_region }}"
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ipv6: "::/0"
          - proto: udp
            from_port: 10000
            to_port: 10000
            cidr_ip: "0.0.0.0/0"
          - proto: udp
            from_port: 10000
            to_port: 10000
            cidr_ipv6: "::/0"
          - proto: tcp
            from_port: 4096
            to_port: 4096
            cidr_ip: "10.0.0.0/24"
          - proto: tcp
            from_port: 4096
            to_port: 4096
            cidr_ipv6: "2406:da1a:670:2600::/56"
        tags: "{'name':'jitsi-videobridge', 'env':'production'}"

    - name: create security group for ssh
      ec2_group:
        name: SSH
        description: SSH security group
        vpc_id: "{{ ec2_vpcid }}"
        region: "{{ ec2_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ipv6: ::/0
        tags: "{'name':'SSH', 'env':'production'}"

    - name: Create subnet for jitsi meet servers
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ ec2_vpcid }}"
        cidr: 10.0.5.0/24
        tags:
          Name: jitsi videobridge
      register: jitsi_videobridge_subnet

    - name: try creating a key pair with name of an already existing keypair
      ec2_key:
        name: collabor8-backend.pem
        force: false
        key_material: "{{ item }}"
      with_file: /Users/brajendrakumar/.ssh/id_rsa

    - name: Launch jitsi videobridge instance
      ec2:
        keypair: "{{ ec2_keypair }}"
        group: ['SSH', 'jitsi-videobridge']
        type: c5.large
        image: ami-02d55cb47e83a99a0
        region: "{{ ec2_region }}"
        instance_tags:
          name: jitsi-videobridge
          env: production
        exact_count: 1
        count_tag:
          name: jitsi-videobridge
          env: production
        wait: true
        vpc_subnet_id: "{{ jitsi_videobridge_subnet.subnet.id }}"
      when: not ansible_check_mode
      register: ec2

    - name: Create volume ec2 volume
      ec2_vol:
        instance: "{{ item.id }}"
        volume_size: "20"
        region: "{{ ec2_region }}"
        delete_on_termination: true
        device_name: /dev/sdf
      loop: "{{ ec2.instances }}"
      register: ec2_vol
      tags: "{'name':'jitsi-videobridge', 'env':'production'}"

    - debug:
        msg:
          - "Server private IPv4: {{ item.private_ip }}"
      when: not ansible_check_mode
      loop: "{{ ec2.instances }}"
