---

# only set this key, otherwise the jitsi installer thinks that it already installed the nginx files

- name: Get my public IP
  ipify_facts:
  when: ipify_public_ip is undefined
  tags:
    - jitsi

- include: packages.yml
  tags:
    - jitsi

- include: jitsi-videobridge.yml
  tags:
    - jitsi

- name: Jitsi | set NPROC
  replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultLimitNPROC=$'
    replace: 'DefaultLimitNPROC=65000'
  notify: reload systemctl
  tags:
    - jitsi

- name: Jitsi | set TasksMax
  replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultTasksMax=$'
    replace: 'DefaultTasksMax=65000'
  notify: reload systemctl
  tags:
    - jitsi

- name: Jitsi | set NOFILE
  replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultLimitNOFILE=$'
    replace: 'DefaultLimitNOFILE=65000'
  notify: reload systemctl
  tags:
    - jitsi




