---

- name: Remove deprecated repo filename.
  file:
    path: /etc/apt/sources.list.d/jitsi_stable.list
    state: absent

- name: Remove deprecated repo filename.
  file:
    path: /etc/apt/sources.list.d/jitsi_unstable.list
    state: absent

- name: Determine repo strategy.
  set_fact:
    jitsi_strategy: "{{ 'unstable' if jitsi_version == 'nightly' else 'stable' }}"


- name: Configure signing key for Jitsi repository.
  apt_key:
    id: 66A9CD0595D6AFA247290D3BEF8B479E2DC1389C
    url: "https://download.jitsi.org/jitsi-key.gpg.key"
    state: present

- name: Install Jitsi apt repo.
  apt_repository:
    repo: "{{ item.value.repo_url }}"
    state: "{{ 'present' if jitsi_strategy == item.key else 'absent' }}"
    filename: /etc/apt/sources.list.d/jitsi_meet
  with_dict: "{{ jitsi_meet_apt_repos }}"

- name: Install Jitsi Videobridge
  apt:
    name: jitsi-videobridge2
    state: latest
    update_cache: yes
    cache_valid_time: 3600
