---
- include_tasks: install.yml
- name: Backup old jibri.jar file
  copy:
    src: /opt/jitsi/jibri/jibri.jar
    dest: /opt/jitsi/jibri/jibri-backup.jar
    remote_src: true

- name: Copy local .jar file
  copy:
    src: jibri-8.0-SNAPSHOT-jar-with-dependencies.jar
    dest: /opt/jitsi/jibri/jibri.jar
    mode: '0644'
    owner: root
    group: root
  notify: Restart jibri

- name: Add config of jibri
  template:
    src: config.json.j2
    dest: /etc/jitsi/jibri/config.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart jibri
  tags:
    - jibri_config

- name: Install upload packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - s3cmd
    - jq

- name: Add S3 config file
  template:
    src: s3cmd.cfg
    dest: "{{ jibri_recording_S3_config_path }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - jibri_config

- name: Add upload_streamfile.sh
  template:
    src: upload_streamfile.sh.j2
    dest: "{{ jibri_recording_S3_custom_script_path }}"
    owner: root
    group: root
    mode: '0755'
  tags:
    - jibri_config

- name: Add cronjob file
  template:
    src: remove_old_recordings.sh.j2
    dest: "/usr/local/bin/remove_old_recordings.sh"
    mode: '0755'
    owner: root
    group: root
  tags:
    - jibri_config

- name: Add cronjobs
  cron:
    name: "Delete old recordings {{ item }}"
    hour: "1"
    minute: "5"
    job: "/usr/local/bin/remove_old_recordings.sh {{ item }} > /dev/null 2>&1"
  loop:
    - '/srv/recordings'
  tags:
    - jibri_config

- name: cron to restart jibri nightly
  cron:
    name: restart jibri
    hour: "3"
    minute: "0"
    user: root
    job: "/usr/sbin/service jibri restart >> /var/log/jitsi/restart_jibri.log 2>&1"
    cron_file: restart_jibri
  tags:
    - cron
    - jibri_config

- name: Enable jibri service
  service:
    name: jibri
    state: started
    enabled: yes
