---
# Copy the original files. (accordingly force:no)
- name: Backup old jitsi-meet.
  copy:
    src: /usr/share/jitsi-meet
    dest: "/usr/share/jitsi-meet-bkp-original"
    force: no
    remote_src: yes
  tags:
    jitsi

- name: Remove backuped jitsi-meet.
  file:
    path: /usr/share/jitsi-meet
    state: absent
  tags: jitsi

- name: Copy SWITCH jitsi-meet build
  unarchive:
    src: jitsi-meet.tar.bz2
    dest: /usr/share/
    owner: root
    group: root
    creates: /usr/share/jitsi-meet
  tags:
    jitsi
